### ISSUE TITLE
Installation guide for dummies , pretty please?

### ISSUE THREAD

**Issue by gromegrom** [janpaul123/delayed-scroll-restoration-polyfill#4]
Hi, I really need to install this but my knowlege is limited.
Any chance you could make step by step intallation guide including latest version of the file for dummies like me.
Huge thank you!

**Comment by trotzig** [comment]
Hi @gromegrom, thanks for the report! I agree that it's a little unclear. I added another way of installing the polyfill (directly from unpkg.com) to the README, maybe that can help out?
